config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
      registrations: 'api/v1/registrations',
      sessions: 'api/v1/sessions',
      passwords: 'api/v1/passwords'
    }

    namespace :api do
      namespace :v1, defaults: { format: :json } do
        resources :permissions
        resources :roles
        resources :team_members
        resources :minutes
        resources :monthly_schedules
        resources :manuals
        resources :file_uploads
        resources :folders
        resources :attendance_confirmations
        resources :meetings
        resources :task_comments
        resources :tasks
        resources :teams
        resources :attendances
        resources :events
        resources :members do
          member do
            patch :reactivate
          end
        end
      end
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :folder
end

app/controllers/api/v1/file_uploads_controller.rb
module Api
  module V1
    class FileUploadsController < Api::V1::ApiController
      before_action :set_file_upload, only: %i[ show edit update destroy ]

      # GET /file_uploads
      def index
        @file_uploads = FileUpload.all
      end

      # GET /file_uploads/1
      def show
      end

      # GET /file_uploads/new
      def new
        @file_upload = FileUpload.new
      end

      # GET /file_uploads/1/edit
      def edit
      end

      # POST /file_uploads
      def create
        @file_upload = FileUpload.new(file_upload_params)

        if @file_upload.save
          redirect_to @file_upload, notice: "File upload was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /file_uploads/1
      def update
        if @file_upload.update(file_upload_params)
          redirect_to @file_upload, notice: "File upload was successfully updated.", status: :see_other
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /file_uploads/1
      def destroy
        @file_upload.destroy!
        redirect_to file_uploads_url, notice: "File upload was successfully destroyed.", status: :see_other
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_file_upload
          @file_upload = FileUpload.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def file_upload_params
          params.require(:file_upload).permit(:name, :size, :url, :folder_id, :deleted_at)
        end
    end
  end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_file_upload.html.erb
<div id="<%= dom_id file_upload %>">
  <p>
    <strong>Name:</strong>
    <%= file_upload.name %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= file_upload.size %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= file_upload.url %>
  </p>

  <p>
    <strong>Folder:</strong>
    <%= file_upload.folder_id %>
  </p>

  <p>
    <strong>Deleted at:</strong>
    <%= file_upload.deleted_at %>
  </p>

</div>

app/views/file_uploads/_form.html.erb
<%= form_with(model: file_upload) do |form| %>
  <% if file_upload.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(file_upload.errors.count, "error") %> prohibited this file_upload from being saved:</h2>

      <ul>
        <% file_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :folder_id, style: "display: block" %>
    <%= form.text_field :folder_id %>
  </div>

  <div>
    <%= form.label :deleted_at, style: "display: block" %>
    <%= form.datetime_field :deleted_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<h1>Editing file upload</h1>

<%= render "form", file_upload: @file_upload %>

<br>

<div>
  <%= link_to "Show this file upload", @file_upload %> |
  <%= link_to "Back to file uploads", file_uploads_path %>
</div>

app/views/file_uploads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>File uploads</h1>

<div id="file_uploads">
  <% @file_uploads.each do |file_upload| %>
    <%= render file_upload %>
    <p>
      <%= link_to "Show this file upload", file_upload %>
    </p>
  <% end %>
</div>

<%= link_to "New file upload", new_file_upload_path %>

app/views/file_uploads/new.html.erb
<h1>New file upload</h1>

<%= render "form", file_upload: @file_upload %>

<br>

<div>
  <%= link_to "Back to file uploads", file_uploads_path %>
</div>

app/views/file_uploads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @file_upload %>

<div>
  <%= link_to "Edit this file upload", edit_file_upload_path(@file_upload) %> |
  <%= link_to "Back to file uploads", file_uploads_path %>

  <%= button_to "Destroy this file upload", @file_upload, method: :delete %>
</div>