config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
      registrations: 'api/v1/registrations',
      sessions: 'api/v1/sessions',
      passwords: 'api/v1/passwords'
    }

    namespace :api do
      namespace :v1, defaults: { format: :json } do
        resources :permissions
        resources :roles
        resources :team_members
        resources :minutes
        resources :monthly_schedules
        resources :manuals
        resources :file_uploads
        resources :folders
        resources :attendance_confirmations
        resources :meetings
        resources :task_comments
        resources :tasks
        resources :teams
        resources :attendances
        resources :events
        resources :members do
          member do
            patch :reactivate
          end
        end
      end
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :team
end

app/controllers/api/v1/meetings_controller.rb
module Api
  module V1
    class MeetingsController < Api::V1::ApiController
      before_action :set_meeting, only: %i[ show edit update destroy ]

      # GET /meetings
      def index
        @meetings = Meeting.all
      end

      # GET /meetings/1
      def show
      end

      # GET /meetings/new
      def new
        @meeting = Meeting.new
      end

      # GET /meetings/1/edit
      def edit
      end

      # POST /meetings
      def create
        @meeting = Meeting.new(meeting_params)

        if @meeting.save
          redirect_to @meeting, notice: "Meeting was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /meetings/1
      def update
        if @meeting.update(meeting_params)
          redirect_to @meeting, notice: "Meeting was successfully updated.", status: :see_other
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /meetings/1
      def destroy
        @meeting.destroy!
        redirect_to meetings_url, notice: "Meeting was successfully destroyed.", status: :see_other
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_meeting
          @meeting = Meeting.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def meeting_params
          params.require(:meeting).permit(:team_id, :title, :date, :mode, :url, :location, :latitude, :longitude, :deleted_at)
        end
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :team_id, style: "display: block" %>
    <%= form.text_field :team_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :mode, style: "display: block" %>
    <%= form.number_field :mode %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :deleted_at, style: "display: block" %>
    <%= form.datetime_field :deleted_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <p>
    <strong>Team:</strong>
    <%= meeting.team_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= meeting.title %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= meeting.date %>
  </p>

  <p>
    <strong>Mode:</strong>
    <%= meeting.mode %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= meeting.url %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= meeting.location %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= meeting.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= meeting.longitude %>
  </p>

  <p>
    <strong>Deleted at:</strong>
    <%= meeting.deleted_at %>
  </p>

</div>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meetings</h1>

<div id="meetings">
  <% @meetings.each do |meeting| %>
    <%= render meeting %>
    <p>
      <%= link_to "Show this meeting", meeting %>
    </p>
  <% end %>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting %>

<div>
  <%= link_to "Edit this meeting", edit_meeting_path(@meeting) %> |
  <%= link_to "Back to meetings", meetings_path %>

  <%= button_to "Destroy this meeting", @meeting, method: :delete %>
</div>