config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
      registrations: 'api/v1/registrations',
      sessions: 'api/v1/sessions',
      passwords: 'api/v1/passwords'
    }

    namespace :api do
      namespace :v1, defaults: { format: :json } do
        resources :permissions
        resources :roles
        resources :team_members
        resources :minutes
        resources :monthly_schedules
        resources :manuals
        resources :file_uploads
        resources :folders
        resources :attendance_confirmations
        resources :meetings
        resources :task_comments
        resources :tasks
        resources :teams
        resources :attendances
        resources :events
        resources :members do
          member do
            patch :reactivate
          end
        end
      end
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/task_comment.rb
class TaskComment < ApplicationRecord
  belongs_to :task
  belongs_to :member
end

app/controllers/api/v1/task_comments_controller.rb
module Api
  module V1
    class TaskCommentsController < Api::V1::ApiController
      before_action :set_task_comment, only: %i[ show edit update destroy ]

      # GET /task_comments
      def index
        @task_comments = TaskComment.all
      end

      # GET /task_comments/1
      def show
      end

      # GET /task_comments/new
      def new
        @task_comment = TaskComment.new
      end

      # GET /task_comments/1/edit
      def edit
      end

      # POST /task_comments
      def create
        @task_comment = TaskComment.new(task_comment_params)

        if @task_comment.save
          redirect_to @task_comment, notice: "Task comment was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /task_comments/1
      def update
        if @task_comment.update(task_comment_params)
          redirect_to @task_comment, notice: "Task comment was successfully updated.", status: :see_other
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /task_comments/1
      def destroy
        @task_comment.destroy!
        redirect_to task_comments_url, notice: "Task comment was successfully destroyed.", status: :see_other
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_task_comment
          @task_comment = TaskComment.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def task_comment_params
          params.require(:task_comment).permit(:body, :task_id, :member_id, :deleted_at)
        end
    end
  end
end

app/helpers/task_comments_helper.rb
module TaskCommentsHelper
end

app/views/task_comments/_form.html.erb
<%= form_with(model: task_comment) do |form| %>
  <% if task_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task_comment.errors.count, "error") %> prohibited this task_comment from being saved:</h2>

      <ul>
        <% task_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>

  <div>
    <%= form.label :member_id, style: "display: block" %>
    <%= form.text_field :member_id %>
  </div>

  <div>
    <%= form.label :deleted_at, style: "display: block" %>
    <%= form.datetime_field :deleted_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/task_comments/_task_comment.html.erb
<div id="<%= dom_id task_comment %>">
  <p>
    <strong>Body:</strong>
    <%= task_comment.body %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= task_comment.task_id %>
  </p>

  <p>
    <strong>Member:</strong>
    <%= task_comment.member_id %>
  </p>

  <p>
    <strong>Deleted at:</strong>
    <%= task_comment.deleted_at %>
  </p>

</div>

app/views/task_comments/edit.html.erb
<h1>Editing task comment</h1>

<%= render "form", task_comment: @task_comment %>

<br>

<div>
  <%= link_to "Show this task comment", @task_comment %> |
  <%= link_to "Back to task comments", task_comments_path %>
</div>

app/views/task_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Task comments</h1>

<div id="task_comments">
  <% @task_comments.each do |task_comment| %>
    <%= render task_comment %>
    <p>
      <%= link_to "Show this task comment", task_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New task comment", new_task_comment_path %>

app/views/task_comments/new.html.erb
<h1>New task comment</h1>

<%= render "form", task_comment: @task_comment %>

<br>

<div>
  <%= link_to "Back to task comments", task_comments_path %>
</div>

app/views/task_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task_comment %>

<div>
  <%= link_to "Edit this task comment", edit_task_comment_path(@task_comment) %> |
  <%= link_to "Back to task comments", task_comments_path %>

  <%= button_to "Destroy this task comment", @task_comment, method: :delete %>
</div>