config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
      registrations: 'api/v1/registrations',
      sessions: 'api/v1/sessions',
      passwords: 'api/v1/passwords'
    }

    namespace :api do
      namespace :v1, defaults: { format: :json } do
        resources :permissions
        resources :roles
        resources :team_members
        resources :minutes
        resources :monthly_schedules
        resources :manuals
        resources :file_uploads
        resources :folders
        resources :attendance_confirmations
        resources :meetings
        resources :task_comments
        resources :tasks
        resources :teams
        resources :attendances
        resources :events
        resources :members do
          member do
            patch :reactivate
          end
        end
      end
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/monthly_schedule.rb
class MonthlySchedule < ApplicationRecord
  belongs_to :created_by
end

app/controllers/api/v1/monthly_schedules_controller.rb
module Api
  module V1
    class MonthlySchedulesController < Api::V1::ApiController
      before_action :set_monthly_schedule, only: %i[ show edit update destroy ]

      # GET /monthly_schedules
      def index
        @monthly_schedules = MonthlySchedule.all
      end

      # GET /monthly_schedules/1
      def show
      end

      # GET /monthly_schedules/new
      def new
        @monthly_schedule = MonthlySchedule.new
      end

      # GET /monthly_schedules/1/edit
      def edit
      end

      # POST /monthly_schedules
      def create
        @monthly_schedule = MonthlySchedule.new(monthly_schedule_params)

        if @monthly_schedule.save
          redirect_to @monthly_schedule, notice: "Monthly schedule was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /monthly_schedules/1
      def update
        if @monthly_schedule.update(monthly_schedule_params)
          redirect_to @monthly_schedule, notice: "Monthly schedule was successfully updated.", status: :see_other
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /monthly_schedules/1
      def destroy
        @monthly_schedule.destroy!
        redirect_to monthly_schedules_url, notice: "Monthly schedule was successfully destroyed.", status: :see_other
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_monthly_schedule
          @monthly_schedule = MonthlySchedule.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def monthly_schedule_params
          params.require(:monthly_schedule).permit(:title, :description, :created_by_id, :scheduled_month, :status, :due_date, :deleted_at)
        end
    end
  end
end

app/helpers/monthly_schedules_helper.rb
module MonthlySchedulesHelper
end

app/views/monthly_schedules/_form.html.erb
<%= form_with(model: monthly_schedule) do |form| %>
  <% if monthly_schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(monthly_schedule.errors.count, "error") %> prohibited this monthly_schedule from being saved:</h2>

      <ul>
        <% monthly_schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :created_by_id, style: "display: block" %>
    <%= form.text_field :created_by_id %>
  </div>

  <div>
    <%= form.label :scheduled_month, style: "display: block" %>
    <%= form.text_field :scheduled_month %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :deleted_at, style: "display: block" %>
    <%= form.datetime_field :deleted_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/monthly_schedules/_monthly_schedule.html.erb
<div id="<%= dom_id monthly_schedule %>">
  <p>
    <strong>Title:</strong>
    <%= monthly_schedule.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= monthly_schedule.description %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= monthly_schedule.created_by_id %>
  </p>

  <p>
    <strong>Scheduled month:</strong>
    <%= monthly_schedule.scheduled_month %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= monthly_schedule.status %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= monthly_schedule.due_date %>
  </p>

  <p>
    <strong>Deleted at:</strong>
    <%= monthly_schedule.deleted_at %>
  </p>

</div>

app/views/monthly_schedules/edit.html.erb
<h1>Editing monthly schedule</h1>

<%= render "form", monthly_schedule: @monthly_schedule %>

<br>

<div>
  <%= link_to "Show this monthly schedule", @monthly_schedule %> |
  <%= link_to "Back to monthly schedules", monthly_schedules_path %>
</div>

app/views/monthly_schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Monthly schedules</h1>

<div id="monthly_schedules">
  <% @monthly_schedules.each do |monthly_schedule| %>
    <%= render monthly_schedule %>
    <p>
      <%= link_to "Show this monthly schedule", monthly_schedule %>
    </p>
  <% end %>
</div>

<%= link_to "New monthly schedule", new_monthly_schedule_path %>

app/views/monthly_schedules/new.html.erb
<h1>New monthly schedule</h1>

<%= render "form", monthly_schedule: @monthly_schedule %>

<br>

<div>
  <%= link_to "Back to monthly schedules", monthly_schedules_path %>
</div>

app/views/monthly_schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monthly_schedule %>

<div>
  <%= link_to "Edit this monthly schedule", edit_monthly_schedule_path(@monthly_schedule) %> |
  <%= link_to "Back to monthly schedules", monthly_schedules_path %>

  <%= button_to "Destroy this monthly schedule", @monthly_schedule, method: :delete %>
</div>